name: Node.js CI

on:
  push:
    branches: [US1-B25-CI-con-github-actions]
  pull_request:
    branches: [US1-B25-CI-con-github-actions]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm lint
      - run: npm test
